update validation step

diff --git a/.github/workflows/integration-install.yml b/.github/workflows/integration-install.yml
--- a/.github/workflows/integration-install.yml
+++ b/.github/workflows/integration-install.yml
@@ -17,11 +17,19 @@ jobs:
       - name: Validate Command is Installed
         shell: bash
         run: |
-          if ! command -v draft &> /dev/null
+          if command -v /home/runner/.local/bin/draft &> /dev/null
           then
-              echo "draft could not be found"
-              exit 1
+              echo "install_dir=/home/runner/.local/bin/draft" >> $GITHUB_ENV
+          elif command -v /usr/local/bin/draft &> /dev/null 
+          then
+            echo "install_dir=/usr/local/bin/draft" >> $GITHUB_ENV
+          elif command -v /c/Users/runneradmin/.local/bin/draft &> /dev/null
+          then
+            echo "install_dir=/c/Users/runneradmin/.local/bin/draft" >> $GITHUB_ENV
+          else 
+            echo "B2k CLI is not found"
+            exit 1
           fi
       - name: Validate Draft Command Runs
         shell: bash
-        run: draft -h
+        run: ${{ env.install_dir }} -h
